baseURL = 'https://punchdrunker.tokyo/'
languageCode = 'ja-jp'
theme = 'paper'
title = 'punchdrunker.log'
googleAnalytics = 'G-S19W8CQGEE'

[params]
  twitter = 'punchdrunker'
  github = 'punchdrunker'
  rss = true
